### ISSUE TITLE
allow to replace `ordrers` 

### ISSUE THREAD

**Issue by pashaie** [sassoftware/postgrest-client#19]
Some times we need to replace previous settings. For example we create a query with default order, later user may decide to change order, but with current implementation we cannot reset or replace order or any other settings of query  because of immutable design.
I suggest to change order to something like this:
```typescript
  order<O extends Order<QO> = Order<QO>>(order: O[], replace = false) {    
    return replace ? this.#clone({ order }) : this.#clone({ order: [...this.#props.order, ...order] });
  }
```

more over, it would be nice to have a `fromObject`  function that  could create a new query instance from `toObject` function output,

**Comment by bojan88** [comment]
Thanks for the suggestions.

We might be adding something like `.mut()` method to make the whole object mutable, but that's currently not a priority and it might never land as a feature.

`fromObject` is interesting, and we might add it at some point if it can be done without much code.

For your problem you can define a base query with no order, assign another with default order and one more if the order changes. Here's some pseudo code to illustrate:
```
let query = pgClient.query(...).select(...);
if (/* user order set */) {
  query = query.order(/* user order */)
}  else {
  query = query.order(/* default order */)
}

const baseQuery = pgClient.query(...).select(...);
return userOrder ? baseQuery.order(...) : baseQuery.order(/* default order */);
```
